name: Keep App Awake

on:
  schedule:
    # Runs at hour 0, 11, and 22 every day
    - cron: "0 */11 * * *"
  workflow_dispatch: # Allows you to manually trigger it for testing

jobs:
  ping_url:
    runs-on: ubuntu-latest
    steps:
      - name: Ping URL
        run: |
          curl https://utilizing-llms-for-hyper-personalized-diet-workout-plans-vqevz.streamlit.app/
